kind: Secret
apiVersion: v1
metadata:
  name: credentials
stringData:
  config.json: |-
    {
      "tenants": {
        "default": {
          "root_users": {
            "admin@styra.local": {
              "encrypted_password": "",
              "password": "CHANGEME"
            }
          }
        }
      }
    }
